import { PaymentRequest, SummaryData } from '@/types';

export const mockSummary: SummaryData = {
  totalShops: 45,
  totalHospitals: 23,
  totalInstitutes: 38,
  totalMarketplaceProducts: 127,
  pendingRequests: 12,
};

export const mockRequests: PaymentRequest[] = [
  {
    id: '1',
    type: 'shop',
    resourceId: 'shop-1',
    resourceName: 'Tech Valley Electronics',
    ownerName: 'Ahmad Hassan',
    ownerId: 'owner-1',
    owner: {
      id: 'owner-1',
      name: 'Ahmad Hassan',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ahmad',
    },
    amount: 15000,
    currency: 'PKR',
    status: 'pending',
    images: ['https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800'],
    notes: 'Monthly subscription payment for premium listing',
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    type: 'hospital',
    resourceId: 'hospital-1',
    resourceName: 'City Care Hospital',
    ownerName: 'Dr. Fatima Ali',
    ownerId: 'owner-2',
    owner: {
      id: 'owner-2',
      name: 'Dr. Fatima Ali',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Fatima',
    },
    amount: 25000,
    currency: 'PKR',
    status: 'pending',
    images: ['https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800'],
    notes: 'Annual listing renewal payment',
    createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '3',
    type: 'education',
    resourceId: 'institute-1',
    resourceName: 'Bright Future Academy',
    ownerName: 'Prof. Muhammad Younis',
    ownerId: 'owner-3',
    owner: {
      id: 'owner-3',
      name: 'Prof. Muhammad Younis',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Muhammad',
    },
    amount: 18000,
    currency: 'PKR',
    status: 'pending',
    images: ['https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800'],
    notes: 'Featured listing upgrade payment',
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '4',
    type: 'marketplace',
    resourceId: 'product-1',
    resourceName: 'Premium Office Furniture Set',
    ownerName: 'Sara Khan',
    ownerId: 'owner-4',
    owner: {
      id: 'owner-4',
      name: 'Sara Khan',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sara',
    },
    amount: 8000,
    currency: 'PKR',
    status: 'pending',
    images: ['https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=800'],
    notes: 'Seller verification payment',
    createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '5',
    type: 'shop',
    resourceId: 'shop-2',
    resourceName: 'Fashion Hub Boutique',
    ownerName: 'Ayesha Malik',
    ownerId: 'owner-5',
    owner: {
      id: 'owner-5',
      name: 'Ayesha Malik',
      avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Ayesha',
    },
    amount: 12000,
    currency: 'PKR',
    status: 'pending',
    images: ['https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=800'],
    notes: 'Premium placement fee',
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
